# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class MageServiceStub(object):
    """O serviço que cada jogador (servidor gRPC) tem de implementar
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CastSpell = channel.unary_unary(
                '/projetors.MageService/CastSpell',
                request_serializer=game__pb2.SpellRequest.SerializeToString,
                response_deserializer=game__pb2.SpellResponse.FromString,
                )
        self.UpdatePosition = channel.unary_unary(
                '/projetors.MageService/UpdatePosition',
                request_serializer=game__pb2.MoveRequest.SerializeToString,
                response_deserializer=game__pb2.Empty.FromString,
                )
        self.SyncState = channel.unary_unary(
                '/projetors.MageService/SyncState',
                request_serializer=game__pb2.StateRequest.SerializeToString,
                response_deserializer=game__pb2.Empty.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/projetors.MageService/Heartbeat',
                request_serializer=game__pb2.Ping.SerializeToString,
                response_deserializer=game__pb2.Pong.FromString,
                )


class MageServiceServicer(object):
    """O serviço que cada jogador (servidor gRPC) tem de implementar
    """

    def CastSpell(self, request, context):
        """Chamado quando um mago lança um feitiço contra ti
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePosition(self, request, context):
        """Chamado para avisar os outros que entraste numa nova sala
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Chamado para sincronizar o estado (Mana/Vida) se necessário
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Um simples "estou vivo" para manter a rede ativa
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CastSpell': grpc.unary_unary_rpc_method_handler(
                    servicer.CastSpell,
                    request_deserializer=game__pb2.SpellRequest.FromString,
                    response_serializer=game__pb2.SpellResponse.SerializeToString,
            ),
            'UpdatePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePosition,
                    request_deserializer=game__pb2.MoveRequest.FromString,
                    response_serializer=game__pb2.Empty.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=game__pb2.StateRequest.FromString,
                    response_serializer=game__pb2.Empty.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=game__pb2.Ping.FromString,
                    response_serializer=game__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'projetors.MageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MageService(object):
    """O serviço que cada jogador (servidor gRPC) tem de implementar
    """

    @staticmethod
    def CastSpell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projetors.MageService/CastSpell',
            game__pb2.SpellRequest.SerializeToString,
            game__pb2.SpellResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projetors.MageService/UpdatePosition',
            game__pb2.MoveRequest.SerializeToString,
            game__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projetors.MageService/SyncState',
            game__pb2.StateRequest.SerializeToString,
            game__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projetors.MageService/Heartbeat',
            game__pb2.Ping.SerializeToString,
            game__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
